// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_Locadora5.Infra.ORM.ParceiroModule;

namespace e_Locadora5.Infra.ORM.Migrations
{
    [DbContext(typeof(LocadoraDbContext))]
    [Migration("20211008144755_CriacaoDeTabelas")]
    partial class CriacaoDeTabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("e_Locadora5.Dominio.ClientesModule.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("CPF")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Endereco")
                        .HasColumnType("VARCHAR(110)");

                    b.Property<string>("Nome")
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("RG")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Telefone")
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("Id");

                    b.ToTable("TBCliente");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.CondutoresModule.Condutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("INT");

                    b.Property<string>("Cpf")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Endereco")
                        .HasColumnType("VARCHAR(110)");

                    b.Property<string>("Nome")
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("NumeroCNH")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Rg")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Telefone")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<DateTime>("ValidadeCNH")
                        .HasColumnType("DATE");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("TBCondutor");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.CupomModule.Cupom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("DATE");

                    b.Property<string>("Nome")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int>("ParceiroId")
                        .HasColumnType("INT");

                    b.Property<decimal>("ValorFixo")
                        .HasColumnType("DECIMAL(18,17)");

                    b.Property<decimal>("ValorMinimo")
                        .HasColumnType("DECIMAL(18,17)");

                    b.Property<int>("ValorPercentual")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("ParceiroId");

                    b.ToTable("TBCupom");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.FuncionarioModule.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("DATE");

                    b.Property<string>("Nome")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("NumeroCpf")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("NUMERIC(38,17)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("TBFuncionario");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.GrupoVeiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("planoDiarioValorDiario")
                        .HasColumnType("float");

                    b.Property<double>("planoDiarioValorKm")
                        .HasColumnType("float");

                    b.Property<double>("planoKmControladoQuantidadeKm")
                        .HasColumnType("float");

                    b.Property<double>("planoKmControladoValorDiario")
                        .HasColumnType("float");

                    b.Property<double>("planoKmControladoValorKm")
                        .HasColumnType("float");

                    b.Property<double>("planoKmLivreValorDiario")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("GrupoVeiculo");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.LocacaoModule.Locacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MarcadorCombustivel")
                        .HasColumnType("int");

                    b.Property<double>("caucao")
                        .HasColumnType("float");

                    b.Property<int?>("clienteId")
                        .HasColumnType("int");

                    b.Property<int?>("condutorId")
                        .HasColumnType("int");

                    b.Property<int?>("cupomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataDevolucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataLocacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("emAberto")
                        .HasColumnType("bit");

                    b.Property<bool>("emailEnviado")
                        .HasColumnType("bit");

                    b.Property<int?>("funcionarioId")
                        .HasColumnType("int");

                    b.Property<int?>("grupoVeiculoId")
                        .HasColumnType("int");

                    b.Property<string>("plano")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("quilometragemDevolucao")
                        .HasColumnType("float");

                    b.Property<double>("seguroCliente")
                        .HasColumnType("float");

                    b.Property<double>("seguroTerceiro")
                        .HasColumnType("float");

                    b.Property<double>("valorTotal")
                        .HasColumnType("float");

                    b.Property<int?>("veiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("clienteId");

                    b.HasIndex("condutorId");

                    b.HasIndex("cupomId");

                    b.HasIndex("funcionarioId");

                    b.HasIndex("grupoVeiculoId");

                    b.HasIndex("veiculoId");

                    b.ToTable("Locacao");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.ParceirosModule.Parceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("TBParceiro");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.TaxasServicosModule.TaxasServicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocacaoId")
                        .HasColumnType("int");

                    b.Property<double>("TaxaDiaria")
                        .HasColumnType("float");

                    b.Property<double>("TaxaFixa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LocacaoId");

                    b.ToTable("TaxasServicos");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.VeiculosModule.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("INT");

                    b.Property<int>("CapacidadeOcupantes")
                        .HasColumnType("INT");

                    b.Property<string>("Combustivel")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Cor")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Fabricante")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int?>("GrupoVeiculoId")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupoVeiculo")
                        .HasColumnType("INT");

                    b.Property<string>("Modelo")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("NumeroChassi")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Placa")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int>("QtdLitrosTanque")
                        .HasColumnType("INT");

                    b.Property<int>("QtdPortas")
                        .HasColumnType("INT");

                    b.Property<decimal>("Quilometragem")
                        .HasColumnType("NUMERIC(38,17)");

                    b.Property<string>("TamanhoPortaMalas")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoVeiculoId");

                    b.ToTable("TBVeiculo");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.CondutoresModule.Condutor", b =>
                {
                    b.HasOne("e_Locadora5.Dominio.ClientesModule.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.CupomModule.Cupom", b =>
                {
                    b.HasOne("e_Locadora5.Dominio.ParceirosModule.Parceiro", "Parceiro")
                        .WithMany("Cupons")
                        .HasForeignKey("ParceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parceiro");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.LocacaoModule.Locacao", b =>
                {
                    b.HasOne("e_Locadora5.Dominio.ClientesModule.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteId");

                    b.HasOne("e_Locadora5.Dominio.CondutoresModule.Condutor", "condutor")
                        .WithMany()
                        .HasForeignKey("condutorId");

                    b.HasOne("e_Locadora5.Dominio.CupomModule.Cupom", "cupom")
                        .WithMany()
                        .HasForeignKey("cupomId");

                    b.HasOne("e_Locadora5.Dominio.FuncionarioModule.Funcionario", "funcionario")
                        .WithMany()
                        .HasForeignKey("funcionarioId");

                    b.HasOne("e_Locadora5.Dominio.GrupoVeiculo", "grupoVeiculo")
                        .WithMany()
                        .HasForeignKey("grupoVeiculoId");

                    b.HasOne("e_Locadora5.Dominio.VeiculosModule.Veiculo", "veiculo")
                        .WithMany("Locacoes")
                        .HasForeignKey("veiculoId");

                    b.Navigation("cliente");

                    b.Navigation("condutor");

                    b.Navigation("cupom");

                    b.Navigation("funcionario");

                    b.Navigation("grupoVeiculo");

                    b.Navigation("veiculo");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.TaxasServicosModule.TaxasServicos", b =>
                {
                    b.HasOne("e_Locadora5.Dominio.LocacaoModule.Locacao", null)
                        .WithMany("taxasServicos")
                        .HasForeignKey("LocacaoId");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.VeiculosModule.Veiculo", b =>
                {
                    b.HasOne("e_Locadora5.Dominio.GrupoVeiculo", "GrupoVeiculo")
                        .WithMany()
                        .HasForeignKey("GrupoVeiculoId");

                    b.Navigation("GrupoVeiculo");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.LocacaoModule.Locacao", b =>
                {
                    b.Navigation("taxasServicos");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.ParceirosModule.Parceiro", b =>
                {
                    b.Navigation("Cupons");
                });

            modelBuilder.Entity("e_Locadora5.Dominio.VeiculosModule.Veiculo", b =>
                {
                    b.Navigation("Locacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
